server:
  port: 8091

spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service
          uri: lb://admin-ms
          predicates:
            - Path=/admin/**,/dashboard/**
        - id: customer-service
          uri: lb://customer-ms
          predicates:
            - Path=/api/customers/**,/auth/**,/customer/**
        - id: order-service
          uri: lb://order-ms
          predicates:
            - Path=/orders/**
        - id: food-item-service
          uri: lb://fooditem-ms
          predicates:
            - Path=/api/food-items/**
        - id: inventory-service
          uri: lb://inventoryitem-ms
          predicates:
            - Path=/inventory/**
        - id: notification-service
          uri: lb://notification-ms
          predicates:
            - Path=/api/notifications/**
        - id: kitchen-flow-service
          uri: lb://kitchenflow-ms
          predicates:
            - Path=/kitchen/**
        - id: delivery-service
          uri: lb://delivery-ms
          predicates:
            - Path=/delivery/**
        - id: food-ingredient-mapping-service
          uri: lb://foodingredientmapping-ms
          predicates:
            - Path=/api/food-ingredients/**
        - id: frontend
          uri: http://localhost:3000
          predicates:
            - Path=/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
